# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Grover
email:
description: >- # this means to ignore newlines until "baseurl:"
  SharePoint / Xamarin developer. A place to share come of the cool things I do and create.
  Posts will contain examples from Xamarin, SharePoint Online, SPFx, Office 365, Azure and PowerShell.
twitter_username: groveale
github_username: groveale
minimal_mistakes_skin: dark #default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/London # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Alex Grover"
  avatar : "/assets/images/avatar.png"
  bio    : "SharePoint CSA / Xamarin Developer / AI Enthusiast"
  location : "London, UK"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://groveale.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/groveale"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/groveale"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/groveale"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/groveale"
    # - label: "Instagram"
    #   icon: "fab fa-fw fa-instagram"
    #   url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

google_site_verification: "ByD62wVxv7k7baPGkf8EvPfxKKqcTKx007oG2luD3w8"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-13L4C3HBZX"
    anonymize_ip: false # default